name: Hackademy-Az-TF--CI


on:
  push:
    branches: [main]
    paths-ignore:
      - "App/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  tf-validation:
    runs-on: windows-latest

    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
#        with:
#         terraform_version: 1.1.7
        # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        
#      - name: LS
#        id: ls
#        run: ls -R

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        
      - name: Terraform Init
        id: init
        working-directory: .
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
