name: Hackademy-Az-TF--CD

on:
  push:
    branches: [main]
    paths-ignore:
      - "App/**"
      - ".github/**"
  workflow_dispatch:

  jobs:
    tf-apply:
      runs-on: ubuntu-latest

      steps:
        - name: Azure authentication
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS  }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          #with:
          # terraform_version: 0.13.0
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Checkout
          uses: actions/checkout@v2

        - name: Terraform Format
          id: fmt
          run: terraform fmt -check

        - name: Terraform Init
          id: init
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
          run: terraform init

        - name: Terraform Plan
          id: plan
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
          run: terraform plan --out=tfplan

        - name: Terraform Apply
          id: apply
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID  }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET  }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID  }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID  }}
          run: terraform apply tfplan        

