name: Hackademy-Az-TF--CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "App/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  tf-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
